/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.utp.misiontic.cesardiaz.vista.gui;

import co.edu.utp.misiontic.cesardiaz.controlador.RestauranteGUIController;
import co.edu.utp.misiontic.cesardiaz.exception.PagoException;
import co.edu.utp.misiontic.cesardiaz.modelo.Adicional;
import co.edu.utp.misiontic.cesardiaz.modelo.Corrientazo;
import co.edu.utp.misiontic.cesardiaz.modelo.Mesa;
import co.edu.utp.misiontic.cesardiaz.modelo.OpcionCarne;
import co.edu.utp.misiontic.cesardiaz.modelo.OpcionEnsalada;
import co.edu.utp.misiontic.cesardiaz.modelo.OpcionJugo;
import co.edu.utp.misiontic.cesardiaz.modelo.OpcionPrincipio;
import co.edu.utp.misiontic.cesardiaz.modelo.OpcionSopa;
import co.edu.utp.misiontic.cesardiaz.modelo.Pedido;
import co.edu.utp.misiontic.cesardiaz.vista.gui.modeloui.PedidoTableModel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author ROG
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private RestauranteGUIController controlador;
    private PedidoTableModel pedidoTableModel;

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();

        setSize(800, 600);
        setLocationRelativeTo(null);

        this.controlador = new RestauranteGUIController();

        // Cargar datos
        limpiarDatosMesa();

        cargarListaMesas();
        cargarCombosComida();

        this.pedidoTableModel = new PedidoTableModel();
        tblPedidos.setModel(this.pedidoTableModel);

        tblPedidos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblPedidos.getSelectionModel().addListSelectionListener(evt -> seleccionarPedido());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnNuevoPedido = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtValorMesa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        spnEfectivo = new javax.swing.JSpinner();
        btnPagar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtDevuelta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstMesas = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnEntregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbSopa = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbPrincipio = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbCarne = new javax.swing.JComboBox<>();
        chkEnsalada = new javax.swing.JCheckBox();
        cmbEnsalada = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cmbJugo = new javax.swing.JComboBox<>();
        btnGuardarPedido = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cmbAdicionales = new javax.swing.JComboBox<>();
        btnAgregarAdicional = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurante El Corrientazo");
        getContentPane().setLayout(new java.awt.GridLayout(1, 3));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Mesas"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        btnNuevoPedido.setText("Nuevo Pedido");
        btnNuevoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPedidoActionPerformed(evt);
            }
        });
        jPanel4.add(btnNuevoPedido);

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuenta"));

        jLabel1.setText("Valor a Pagar");

        txtValorMesa.setEditable(false);
        txtValorMesa.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtValorMesa.setText("0");

        jLabel2.setText("Efectivo");

        spnEfectivo.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 500));

        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        jLabel3.setText("Devuelta");

        txtDevuelta.setEditable(false);
        txtDevuelta.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtDevuelta.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValorMesa)
                            .addComponent(spnEfectivo, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPagar))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDevuelta)))
                .addContainerGap())
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtValorMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spnEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDevuelta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        lstMesas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstMesas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstMesasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstMesas);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedidos"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        btnEntregar.setText("Entregar");
        btnEntregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregarActionPerformed(evt);
            }
        });
        jPanel6.add(btnEntregar);

        jPanel2.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jScrollPane2.setViewportView(tblPedidos);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2);

        jLabel4.setText("Cliente");

        jLabel5.setText("Sopa");

        jLabel6.setText("Principio");

        jLabel7.setText("Carne");

        chkEnsalada.setSelected(true);
        chkEnsalada.setText("Ensalada");
        chkEnsalada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEnsaladaActionPerformed(evt);
            }
        });

        jLabel8.setText("Jugo");

        btnGuardarPedido.setText("Guardar");
        btnGuardarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPedidoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Adicionales");

        btnAgregarAdicional.setText("Agregar");

        jScrollPane3.setPreferredSize(new java.awt.Dimension(200, 402));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSopa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCliente)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chkEnsalada, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbPrincipio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbCarne, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbEnsalada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbJugo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardarPedido))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(cmbAdicionales, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarAdicional))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {chkEnsalada, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbSopa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbPrincipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbCarne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkEnsalada)
                    .addComponent(cmbEnsalada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbJugo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAdicionales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarAdicional))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstMesasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstMesasValueChanged
        var mesa = lstMesas.getSelectedValue();
        if (mesa != null) {
            cargarDatosMesa(mesa);
        } else {
            limpiarDatosMesa();
        }
    }//GEN-LAST:event_lstMesasValueChanged

    private void btnEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarActionPerformed
        if (tblPedidos.getSelectedRowCount() == 1) {
            try {
                var row = tblPedidos.getSelectedRow();
                var pedido = this.pedidoTableModel.getDato(row);
                controlador.entregarPedido(pedido);

                this.pedidoTableModel.setDato(row, pedido);
                lstMesasValueChanged(null);

                mostrarMensaje("El pedido se ha entregado exitosamente");
            } catch (SQLException ex) {
                mostrarError("Error entregando pedido", ex);
            }
        }
    }//GEN-LAST:event_btnEntregarActionPerformed

    private void chkEnsaladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEnsaladaActionPerformed
        // TODO add your handling code here:
        if (!chkEnsalada.isSelected()) {
            cmbEnsalada.setEnabled(false);
            cmbEnsalada.setSelectedIndex(-1);
        } else {
            cmbEnsalada.setEnabled(true);
        }
    }//GEN-LAST:event_chkEnsaladaActionPerformed

    private void btnNuevoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPedidoActionPerformed
        if (lstMesas.getSelectedValue() != null) {
            tblPedidos.clearSelection();
            limpiarCamposPedido();
            txtCliente.requestFocus();
        } else {
            mostrarAdvertencia("Debe seleccionar una mesa");
        }
    }//GEN-LAST:event_btnNuevoPedidoActionPerformed

    private void btnGuardarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPedidoActionPerformed
        // TODO Validar campos obligatorios

        // Enviar a guardar a la base de datos
        try {
            var mesa = lstMesas.getSelectedValue();
            Corrientazo almuerzo = null;
            if (chkEnsalada.isSelected()) {
                almuerzo = new Corrientazo(12_000,
                        (OpcionSopa) cmbSopa.getSelectedItem(),
                        (OpcionPrincipio) cmbPrincipio.getSelectedItem(),
                        (OpcionCarne) cmbCarne.getSelectedItem(),
                        (OpcionEnsalada) cmbEnsalada.getSelectedItem(),
                        (OpcionJugo) cmbJugo.getSelectedItem());
            } else {
                almuerzo = new Corrientazo(12_000,
                        (OpcionSopa) cmbSopa.getSelectedItem(),
                        (OpcionPrincipio) cmbPrincipio.getSelectedItem(),
                        (OpcionCarne) cmbCarne.getSelectedItem(),
                        (OpcionJugo) cmbJugo.getSelectedItem());
            }
            var pedido = new Pedido(txtCliente.getText(), almuerzo);

            controlador.guardarPedido(mesa, pedido);

            // Actualizar la tabla de pedidos
            this.pedidoTableModel.addDato(pedido);

            mostrarMensaje("Pedido agregado exitosamente");
        } catch (SQLException ex) {
            mostrarError("Error guardando pedido", ex);
        }
    }//GEN-LAST:event_btnGuardarPedidoActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        try {
            var mesa = lstMesas.getSelectedValue();
            var efectivo = (Integer) spnEfectivo.getValue();
            var devuelta = controlador.pagarMesa(mesa, efectivo);
            
            txtDevuelta.setText(String.format("$ %,d", devuelta));
            
            mostrarMensaje("La cuenta se ha pagado por completo");
            
            lstMesas.clearSelection();
            lstMesasValueChanged(null);
            
        } catch (SQLException | PagoException ex) {
            mostrarError("Error pagando cuenta", ex);
        }
    }//GEN-LAST:event_btnPagarActionPerformed

    private void cargarListaMesas() {
        try {
            var mesas = controlador.listarMesas();

            lstMesas.removeAll();
            var modelo = new DefaultListModel<Mesa>();
            modelo.addAll(mesas);
            lstMesas.setModel(modelo);

        } catch (SQLException ex) {
            mostrarError("Error listando mesas", ex);
        }
    }

    private void cargarCombosComida() {
        try {
            cmbSopa.removeAllItems();
            controlador.listarSopas().forEach(cmbSopa::addItem);

            cmbPrincipio.removeAllItems();
            controlador.listarPrincipios().forEach(cmbPrincipio::addItem);

            cmbCarne.removeAllItems();
            controlador.listarCarnes().forEach(cmbCarne::addItem);

            cmbEnsalada.removeAllItems();
            controlador.listarEnsaladas().forEach(cmbEnsalada::addItem);

            cmbJugo.removeAllItems();
            controlador.listarJugos().forEach(cmbJugo::addItem);

        } catch (SQLException ex) {
            mostrarError("Error consultando alimentos", ex);
        }
    }

    private void cargarDatosMesa(Mesa mesa) {
        try {
            // Cargar el valor a pagar
            var valor = controlador.calcularValorMesa(mesa);
            txtValorMesa.setText(String.format("$ %,d", valor));

            // Cargar los pedidos de la mesa
            var pedidos = controlador.listarPedidos(mesa);
            this.pedidoTableModel.setDatos(pedidos);

        } catch (SQLException ex) {
            mostrarError("Error consultando cuenta de mesa", ex);
        }
    }

    private void limpiarDatosMesa() {
        txtValorMesa.setText(String.format("$ %,d", 0));
        spnEfectivo.setValue(0);
        txtDevuelta.setText(String.format("$ %,d", 0));
    }

    private void seleccionarPedido() {
        if (tblPedidos.getSelectedRowCount() == 1) {
            // Cargar la informacion del pedido en el formulario
            var pedido = pedidoTableModel.getDato(tblPedidos.getSelectedRow());

            txtCliente.setText(pedido.getCliente());
            cmbSopa.setSelectedItem(pedido.getAlmuerzo().getSopa());
            cmbPrincipio.setSelectedItem(pedido.getAlmuerzo().getPrincipio());
            cmbCarne.setSelectedItem(pedido.getAlmuerzo().getCarne());

            if (pedido.getAlmuerzo().getEnsalada() == null) {
                chkEnsalada.setSelected(false);
            } else {
                chkEnsalada.setSelected(true);
                cmbEnsalada.setSelectedItem(pedido.getAlmuerzo().getEnsalada());
            }
            chkEnsaladaActionPerformed(null);

            cmbJugo.setSelectedItem(pedido.getAlmuerzo().getJugo());

            // TODO Agregar los adicionales a la tabla
        } else {
            limpiarCamposPedido();
        }
    }

    private void limpiarCamposPedido() {
        // Limpiar los datos del pedido
        txtCliente.setText("");
        cmbSopa.setSelectedIndex(-1);
        cmbPrincipio.setSelectedIndex(-1);
        cmbCarne.setSelectedIndex(-1);
        cmbEnsalada.setSelectedIndex(-1);
        cmbJugo.setSelectedIndex(-1);

        // TODO Limpiar los adicionales de la tabla
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAdicional;
    private javax.swing.JButton btnEntregar;
    private javax.swing.JButton btnGuardarPedido;
    private javax.swing.JButton btnNuevoPedido;
    private javax.swing.JButton btnPagar;
    private javax.swing.JCheckBox chkEnsalada;
    private javax.swing.JComboBox<Adicional> cmbAdicionales;
    private javax.swing.JComboBox<OpcionCarne> cmbCarne;
    private javax.swing.JComboBox<OpcionEnsalada> cmbEnsalada;
    private javax.swing.JComboBox<OpcionJugo> cmbJugo;
    private javax.swing.JComboBox<OpcionPrincipio> cmbPrincipio;
    private javax.swing.JComboBox<OpcionSopa> cmbSopa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<Mesa> lstMesas;
    private javax.swing.JSpinner spnEfectivo;
    private javax.swing.JTable tblPedidos;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtDevuelta;
    private javax.swing.JTextField txtValorMesa;
    // End of variables declaration//GEN-END:variables

    private void mostrarError(String error, Exception ex) {
        JOptionPane.showMessageDialog(this, error + ": " + ex.getMessage(),
                "Restaurante El Corrientazo", JOptionPane.ERROR_MESSAGE);
    }

    private void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje,
                "Restaurante El Corrientazo", JOptionPane.INFORMATION_MESSAGE);
    }

    private void mostrarAdvertencia(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje,
                "Restaurante El Corrientazo", JOptionPane.WARNING_MESSAGE);
    }

}
